spring:
  application:
    name: SECURITY
  datasource:    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/security?
    username: root
    password: nga
  jpa:    open-in-view: false
    hibernate:
      ddl-auto: update  
    properties :
      hibernate: 
         format_sql : true
         show-sql : true
         generate-ddl : true 